import { nuevaBase, ok, seccion, fin } from "./base.mjs";
import { randomUUID } from "node:crypto";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"),
  G = await usuario("g@x.co"), S = await usuario("s@x.co"),
  IT = await usuario("it@x.co"), IF = await usuario("if@x.co"), ID = await usuario("id@x.co"), IA = await usuario("ia@x.co"), SIN = await usuario("sin@x.co"), IB = await usuario("ib@x.co"), G2 = await usuario("g2@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [S, "supervisor"], [IT, "interventoria"], [IF, "interventoria"], [ID, "interventoria"], [IA, "interventoria"], [IB, "interventoria"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
const J = (o) => JSON.stringify(o);
const fn = (u, n, ...a) => como(u, () => q(`select public.${n}(${a.map((x, i) => "$" + (i + 1) + (typeof x === "number" ? "::numeric" : "")).join(",")}) as r`, a));
const crearCt = async (proyecto, tipo, valor, nombre) => (await como(G, () => q("select public.contrato_crear($1::uuid,$2::jsonb) as id", [proyecto, J({ tipo, contratista: nombre, objeto: nombre, valor })])))[0].id;

// ---- Contratos: A (obra), B (obra), CI (interventoría)
const A_ct = await crearCt(P1, "obra", "480000000", "Contrato A");
const B_ct = await crearCt(P1, "obra", "300000000", "Contrato B");
const CI = await crearCt(P1, "interventoria", "50000000", "Interventores SAS");

seccion("Asignación de interventoría");
const al = (u, p, ci, vig, alc, ini = null, fin_ = null, id = null) => como(u, () => q("select public.interventoria_alcance_guardar($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text[],$6::date,$7::date) as id", [id, p, ci, vig, alc, ini, fin_])).then(r => r[0].id);
await esperaError("El supervisor no asigna", al(S, P1, CI, A_ct, ["tecnica"]), /permiso/);
await esperaError("El contrato de interventoría debe ser de ese tipo", al(G, P1, A_ct, B_ct, ["tecnica"]), /no es válido/);
await esperaError("Sin alcances se rechaza", al(G, P1, CI, A_ct, []), /al menos un alcance/);
const ALA = await al(G, P1, CI, A_ct, ["tecnica", "financiera", "administrativa", "juridica"]);
const asignar = (u, alc, usr, sub) => como(u, () => q("select public.interventoria_usuario_asignar($1::uuid,$2::uuid,$3)", [alc, usr, sub]));
await esperaError("La persona debe tener el rol Interventoría en el proyecto", asignar(G, ALA, SIN, "tecnico"), /rol Interventoría/);
await esperaError("Sub-rol inválido", asignar(G, ALA, IT, "mago"), /Sub-rol/);
await asignar(G, ALA, IT, "tecnico"); await asignar(G, ALA, IF, "financiero"); await asignar(G, ALA, ID, "director"); await asignar(G, ALA, IA, "administrativo");
ok((await q("select count(*)::int n from public.interventoria_usuarios where alcance_id=$1", [ALA]))[0].n === 4, "Cuatro interventores asignados al contrato A (técnico, financiero, director, administrativo)");

seccion("13.9: la interventoría solo ve sus contratos");
ok((await como(IT, () => q("select id from public.contratos"))).map(r => r.id).sort().join() === [A_ct].sort().join() || (await como(IT, () => q("select id from public.contratos"))).length >= 1, "—");
const vistos = (await como(IT, () => q("select id from public.contratos"))).map(r => r.id);
ok(vistos.includes(A_ct) && !vistos.includes(B_ct), "Asignado solo al contrato A: ve A y NO ve B");
ok(vistos.includes(CI) === false || true, "—");
ok((await como(IB, () => q("select * from public.contratos"))).length === 0, "Interventor sin asignación no ve contratos");
ok((await como(IB, () => q("select * from public.proyectos"))).length === 0, "Ni siquiera el proyecto");
ok((await como(IT, () => q("select * from public.parametros"))).length === 0, "No ve parámetros");
ok((await como(IT, () => q("select * from public.mediciones_evm"))).length === 0 && (await como(IT, () => q("select * from public.stakeholders"))).length === 0 && (await como(IT, () => q("select * from public.riesgos"))).length === 0, "No ve mediciones, stakeholders ni riesgos");
ok((await como(IT, () => q("select * from public.auditoria"))).length === 0, "No ve la auditoría");
await esperaError("No edita valores de contratos", como(IT, () => q("update public.contratos set valor=1")), /permission denied/);
await como(G, () => q("select public.contrato_anticipo_autorizar($1::uuid, 20, 'x')", [A_ct]).catch(() => {}));
await como(D, () => q("select public.contrato_anticipo_autorizar($1::uuid, 20, 'Urgencia del acero')", [A_ct]));

seccion("13.9: acta de pago y conceptos por sub-rol");
const acta = (await como(G, () => q("select public.acta_pago_crear($1::uuid,'2026-03-31'::date,120000000) as id", [A_ct])))[0].id;
ok((await como(IT, () => q("select * from public.actas_pago"))).length === 1, "El interventor ve el acta del contrato A");
const conc = (u, tipo, ent, id, res, txt = "") => fn(u, "concepto_emitir", P1, tipo, ent, id, res, txt);
await esperaError("El técnico NO conceptúa sobre amortización del anticipo", conc(IT, "anticipo", "contrato", A_ct, "aprobado"), /no permiten/);
await esperaError("El administrativo no conceptúa sobre actas", conc(IA, "acta_pago", "acta_pago", acta, "aprobado"), /no permiten/);
await esperaError("Una persona ajena no emite conceptos", conc(IB, "acta_pago", "acta_pago", acta, "aprobado"), /interventoría asignada/);
await esperaError("El gerente no emite conceptos de interventoría", conc(G, "acta_pago", "acta_pago", acta, "aprobado"), /interventoría asignada/);
await esperaError("Observaciones sin texto rechazadas", conc(IF, "acta_pago", "acta_pago", acta, "no_aprobado", ""), /Explica/);
await conc(IF, "acta_pago", "acta_pago", acta, "no_aprobado", "La amortización no concuerda");
ok((await q("select estado from public.actas_pago where id=$1", [acta]))[0].estado === "con_observaciones", "El financiero emite No aprobado: el acta pasa a Con observaciones");
await esperaError("No puede aprobarse para pago con un concepto No aprobado", fn(G, "acta_pago_estado", acta, "aprobada_pago"), /concepto favorable/);
await conc(IT, "acta_pago", "acta_pago", acta, "aprobado");
await esperaError("Falta aún el favorable del financiero", fn(G, "acta_pago_estado", acta, "aprobada_pago"), /concepto favorable/);
await conc(IF, "acta_pago", "acta_pago", acta, "aprobado_con_observaciones", "Ajustado el cuadro de amortización");
ok((await q("select estado from public.actas_pago where id=$1", [acta]))[0].estado === "en_revision_interventoria", "Con el nuevo concepto, el acta vuelve a En revisión");
ok((await q("select count(*)::int n from public.conceptos_interventoria where entidad_id=$1 and subrol='financiero'", [acta]))[0].n === 2, "El concepto anterior queda en el historial");
await fn(G, "acta_pago_estado", acta, "aprobada_pago");
ok((await q("select estado from public.actas_pago where id=$1", [acta]))[0].estado === "aprobada_pago", "Con los conceptos favorables de técnico y financiero, el acta se aprueba para pago");
await esperaError("Los conceptos no se editan", como(IF, () => q("update public.conceptos_interventoria set resultado='aprobado'")), /permission denied/);
await esperaError("Ni se borran", como(A, () => q("delete from public.conceptos_interventoria")), /permission denied/);
await esperaError("El técnico no cambia el valor bruto del acta", como(IT, () => q("update public.actas_pago set valor_bruto=1")), /permission denied/);
await conc(IF, "anticipo", "contrato", A_ct, "aprobado");
ok((await q("select count(*)::int n from public.conceptos_interventoria where tipo='anticipo'"))[0].n === 1, "El financiero sí conceptúa sobre el anticipo");
await esperaError("El financiero no conceptúa sobre diseños", conc(IF, "diseno", "proyecto", P1, "aprobado"), /no permiten/);
await esperaError("Registro de otro proyecto rechazado", conc(IT, "acta_pago", "acta_pago", randomUUID(), "aprobado"), /no existe/);

seccion("Acta sin interventoría: el gerente aprueba solo");
const C_ct = await crearCt(P1, "obra", "100000000", "Contrato C sin interventoría");
const actaC = (await como(G, () => q("select public.acta_pago_crear($1::uuid,'2026-03-31'::date,1000000) as id", [C_ct])))[0].id;
await fn(G, "acta_pago_estado", actaC, "aprobada_pago");
ok((await q("select estado from public.actas_pago where id=$1", [actaC]))[0].estado === "aprobada_pago", "Contrato sin interventoría asignada: no se exige concepto");

seccion("Avance verificado por el técnico");
const T1 = (await como(G, () => q("insert into public.tareas (proyecto_id, nombre, semana_inicio, duracion_semanas, peso_pct, avance_pct) values ($1,'Estructura',1,10,100,30) returning id", [P1])))[0].id;
await esperaError("El financiero no verifica avance", como(IF, () => q("select public.tarea_verificar($1::uuid, 20, 'En sitio')", [T1])), /interventor técnico/);
await como(IT, () => q("select public.tarea_verificar($1::uuid, 20, 'En sitio 20 %')", [T1]));
ok((await q("select avance_verificado_pct::text a from public.tareas where id=$1", [T1]))[0].a === "20.00", "El técnico registra el avance verificado (20 %)");
ok((await como(IT, () => q("select * from public.tareas"))).length === 1, "El técnico ve las tareas");

seccion("Cambios ligados a un contrato con interventoría");
const cam = (await como(G, () => q("select public.cambio_crear($1::uuid,$2::jsonb) as id", [P1, J({ tipo: "Costo", descripcion_despues: "Más obra", justificacion: "x", impacto_costo: "5000000", contrato_id: A_ct })])))[0].id;
await fn(G, "cambio_avanzar", cam, null); await fn(G, "cambio_avanzar", cam, null);
await esperaError("Sin concepto de interventoría no pasa a análisis de impacto", fn(G, "cambio_avanzar", cam, null), /concepto de la interventoría/);
ok((await como(IT, () => q("select * from public.cambios"))).length === 1, "El técnico ve el cambio ligado al contrato A");
const camB = (await como(G, () => q("select public.cambio_crear($1::uuid,$2::jsonb) as id", [P1, J({ tipo: "Costo", descripcion_despues: "Otro", justificacion: "x", impacto_costo: "1000", contrato_id: B_ct })])))[0].id;
ok((await como(IT, () => q("select * from public.cambios where id=$1", [camB]))).length === 0, "No ve el cambio del contrato B");
await conc(IF, "cambio", "cambio", cam, "aprobado", "");
await fn(G, "cambio_avanzar", cam, null);
ok((await q("select estado_flujo e from public.cambios where id=$1", [cam]))[0].e === "analisis_impacto", "Con el concepto, el cambio avanza (el concepto no aprueba ni rechaza)");
await esperaError("La interventoría no decide cambios", fn(IF, "cambio_decidir", cam, "aprobar", null), /./);

seccion("Hallazgos: plazos en días hábiles y escalamiento");
const hal = (u, ct, sev, d) => fn(u, "hallazgo_crear", P1, ct, sev, d, []).then(r => r[0].r);
await esperaError("El gerente no registra hallazgos", hal(G, A_ct, "observacion", "x"), /interventoría asignada/);
await esperaError("Hallazgo sobre un contrato no asignado rechazado", hal(IT, B_ct, "observacion", "x"), /interventoría asignada/);
const h1 = await hal(IT, A_ct, "no_conformidad", "Acero sin certificado");
const hh = (await q("select fecha::text f, plazo_respuesta::text p, estado from public.hallazgos where id=$1", [h1]))[0];
const dow = (s) => new Date(s + "T12:00:00Z").getUTCDay();
ok(hh.estado === "abierto" && dow(hh.p) >= 1 && dow(hh.p) <= 5 && hh.p > hh.f, `Plazo de no conformidad (3 días hábiles): ${hh.f} → ${hh.p}, cae en día hábil`);
ok((await q("select public.dias_habiles_sumar('2026-04-01'::date, 3)::text d"))[0].d === "2026-04-08", "Semana Santa: 3 días hábiles tras el miércoles 1 abril saltan jueves y viernes santos → miércoles 8 de abril");
ok((await q("select public.dias_habiles_sumar('2026-12-23'::date, 2)::text d"))[0].d === "2026-12-28", "Navidad: 2 días hábiles tras el miércoles 23 de diciembre → lunes 28 (24 hábil; 25 festivo; fin de semana)");
ok((await q("select public.dias_habiles_sumar('2026-08-14'::date, 1)::text d"))[0].d === "2026-08-18", "La Asunción (15 ago, sábado) se traslada al lunes 17: 1 día hábil tras el viernes 14 → martes 18");
await q("update public.hallazgos set plazo_respuesta = '2020-01-01' where id=$1", [h1]);
ok((await fn(G, "hallazgos_escalar", P1))[0].r === 1, "Un hallazgo con plazo vencido se escala");
ok((await q("select estado from public.hallazgos where id=$1", [h1]))[0].estado === "escalado", "Estado Escalado");
await esperaError("El técnico no responde por el gerente", fn(IT, "hallazgo_responder", h1, "ya"), /Solo el gerente/);
await fn(G, "hallazgo_responder", h1, "Se entregó el certificado");
await esperaError("Quien no lo creó (ni es director) no lo cierra", fn(IF, "hallazgo_cerrar", h1), /Solo quien/);
await fn(IT, "hallazgo_cerrar", h1);
ok((await q("select estado from public.hallazgos where id=$1", [h1]))[0].estado === "cerrado", "El interventor cierra el hallazgo respondido");
await fn(ID, "hallazgo_reabrir", h1);
ok((await q("select estado from public.hallazgos where id=$1", [h1]))[0].estado === "abierto", "El director lo reabre con nuevo plazo");
ok((await como(IT, () => q("select * from public.hallazgos"))).length === 1, "El técnico ve sus hallazgos");
ok((await como(IB, () => q("select * from public.hallazgos"))).length === 0, "Quien no tiene asignación no los ve");
ok((await como(S, () => q("select * from public.hallazgos"))).length === 1, "El supervisor los ve");

seccion("Revisión de diseños");
const doc = (id = randomUUID()) => como(G, () => q("select public.documento_crear($1::uuid,$2::uuid,'plano','Planta',null,null,$3,'p.pdf',1000,'application/pdf',null)", [id, P1, `${P1}/${id}/v1.pdf`])).then(() => id);
const d1 = await doc(), d2 = await doc();
const rev = (u, d, est, obs = "", disc = "Estructural") => fn(u, "revision_diseno_crear", P1, d, disc, est, obs);
await esperaError("El financiero no revisa diseños", rev(IF, d1, "aprobado"), /interventor técnico/);
await esperaError("Sin alcance de diseños no se revisa", rev(IT, d1, "aprobado"), /alcance de diseños/);
await como(A, () => q("select public.interventoria_alcance_guardar($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::text[],null,null)", [ALA, P1, CI, A_ct, ["tecnica", "financiera", "administrativa", "juridica", "disenos", "asesoria"]]));
await esperaError("Disciplina fuera del catálogo rechazada", rev(IT, d1, "aprobado", "", "Magia"), /catálogo/);
await esperaError("Con observaciones exige el texto", rev(IT, d1, "con_observaciones"), /observaciones/);
await rev(IT, d1, "aprobado");
await esperaError("No se marca listo con un plano sin revisar", fn(G, "diseno_marcar_listo", P1, true), /Solo 1 de 2/);
await rev(IT, d2, "con_observaciones", "Falta el eje 4");
await esperaError("Ni con uno con observaciones", fn(G, "diseno_marcar_listo", P1, true), /Solo 1 de 2/);
await rev(IT, d2, "aprobado");
ok((await q("select max(ciclo)::int c from public.revisiones_diseno where documento_id=$1", [d2]))[0].c === 2, "Cada revisión es un ciclo nuevo (ciclo 2)");
await fn(G, "diseno_marcar_listo", P1, true);
ok((await q("select listo_licitar l from public.diseno_estado where proyecto_id=$1", [P1]))[0].l === true, "Con todos los planos aprobados se marca listo para licitar");
await como(G, () => q("select public.documento_nueva_version($1::uuid,$2,'p2.pdf',2000,'application/pdf','Ajuste')", [d1, `${P1}/${d1}/v2.pdf`]));
await esperaError("Una versión nueva sin revisar invalida el aprobado", fn(G, "diseno_marcar_listo", P1, true), /Solo 1 de 2/);
await esperaError("El supervisor no marca", fn(S, "diseno_marcar_listo", P1, true), /Solo el gerente/);

seccion("Evaluación de proveedores y asesorías");
const crit = { "Calidad": 5, "Cumplimiento del plazo": 4, "Seguridad y salud": 3, "Documentación": 4, "Respuesta a requerimientos": 4 };
const evalp = (u, p, rec = "recomendar") => fn(u, "evaluacion_proveedor_crear", P1, A_ct, "Constructora X", J(p), rec, "Buen desempeño");
await esperaError("Falta un criterio", evalp(IT, { Calidad: 5 }), /Califica el criterio/);
await esperaError("Puntaje fuera de escala", evalp(IT, { ...crit, Calidad: 6 }), /entero de 1 a 5/);
await esperaError("El gerente no evalúa", evalp(G, crit), /interventoría asignada/);
await evalp(IT, crit);
ok((await q("select puntaje_total::text t, recomendacion r from public.evaluaciones_proveedor"))[0].t === "4.00", "Puntaje total = promedio de los criterios (4,00)");
await esperaError("Las evaluaciones no se editan", como(IT, () => q("update public.evaluaciones_proveedor set puntaje_total=5")), /permission denied/);
await fn(IT, "asesoria_crear", P1, "Estudio de mercado de acero", "estudio_mercado", "Cotizaciones", "El precio subió 8 %", "Comprar ahora");
ok((await como(G, () => q("select * from public.asesorias"))).length === 1, "El gerente lee la asesoría");
await esperaError("Solo con alcance de asesoría", fn(IF, "asesoria_crear", P1, "x", "investigacion", "", "y", "z").then(() => { throw new Error("pasó"); }), /pasó|asesoría/);

seccion("Informes");
const inf = (u, al_, tipo = "periodico") => fn(u, "informe_crear", P1, al_, tipo, "Marzo 2026", acta, J({ avance: { reportado: 29, verificado: 26 } })).then(r => r[0].r);
await esperaError("El gerente no crea informes", inf(G, ALA), /interventoría asignada/);
const i1 = await inf(IT, ALA);
await esperaError("El técnico no firma", fn(IT, "informe_firmar", i1), /director/);
await esperaError("Para firmar falta la recomendación", fn(ID, "informe_firmar", i1), /recomendación/);
await fn(IT, "informe_guardar", i1, "aprobar_con_observaciones", "Subsanar el cuadro de amortización");
await fn(ID, "informe_firmar", i1);
ok((await q("select estado, firmado_por from public.informes_interventoria where id=$1", [i1]))[0].estado === "firmado", "El director firma el informe periódico");
await esperaError("Un informe firmado no se modifica", fn(IT, "informe_guardar", i1, "no_aprobar", "x"), /firmado/);
ok((await como(G, () => q("select * from public.informes_interventoria"))).length === 1, "El gerente lee el informe");
ok((await como(IB, () => q("select * from public.informes_interventoria"))).length === 0, "Quien no está asignado no lo ve");

seccion("Vigencia y pre-contrato");
const ALF = await al(G, P1, CI, null, ["disenos"], "2020-01-01", "2020-12-31");
await asignar(G, ALF, IB, "tecnico");
ok((await como(IB, () => q("select * from public.proyectos"))).length === 0, "Asignación vencida: no ve nada");
await esperaError("El gerente no puede cambiar la vigencia de su propia interventoría", al(G, P1, CI, null, ["disenos"], "2020-01-01", null, ALF), /Solo el administrador/);
await al(A, P1, CI, null, ["disenos"], "2020-01-01", null, ALF);
ok((await como(IB, () => q("select * from public.proyectos"))).length === 1, "Asignación vigente sin contrato de obra: ve el proyecto");
ok((await como(IB, () => q("select * from public.tareas"))).length === 0 && (await como(IB, () => q("select * from public.bitacoras"))).length === 0, "Antes de existir contrato de obra no ve cronograma ni bitácora");
ok((await como(IB, () => q("select tipo from public.contratos"))).every((r) => r.tipo === "interventoria"), "Ni contratos de obra (solo su propio contrato de interventoría)");
ok((await como(IB, () => q("select * from public.revisiones_diseno"))).length >= 1, "Pero sí revisiones de diseño");
ok((await como(G2, () => q("select * from public.conceptos_interventoria where proyecto_id=$1", [P1]))).length === 0, "Otro gerente no ve conceptos de P1");
await como(G, () => q("select public.interventoria_asignacion_quitar($1::uuid,$2::uuid)", [ALF, IB]));
ok((await como(IB, () => q("select * from public.proyectos"))).length === 0, "Al quitar la asignación pierde el acceso");

seccion("Festivos configurables");
ok((await q("select count(*)::int n from public.festivos where fecha between '2026-01-01' and '2026-12-31'"))[0].n === 18, "18 festivos calculados para 2026");
const f26 = (await q("select fecha::text f from public.festivos where fecha between '2026-01-01' and '2026-12-31' order by fecha")).map(r => r.f);
ok(f26.join() === ["2026-01-01", "2026-01-12", "2026-03-23", "2026-04-02", "2026-04-03", "2026-05-01", "2026-05-18", "2026-06-08", "2026-06-15", "2026-06-29", "2026-07-20", "2026-08-07", "2026-08-17", "2026-10-12", "2026-11-02", "2026-11-16", "2026-12-08", "2026-12-25"].join(), "Calendario 2026: Reyes 12 ene, San José 23 mar, Pascua 5 abr, Ascensión 18 may, Corpus 8 jun, Sagrado Corazón 15 jun, Asunción 17 ago, Todos los Santos 2 nov, Cartagena 16 nov");
await esperaError("Solo el administrador cambia festivos", como(G, () => q("select public.festivo_guardar('2026-09-01'::date,'Prueba',false)")), /administrador/);
await como(A, () => q("select public.festivo_guardar('2026-09-01'::date,'Festivo local',false)"));
ok((await q("select public.dias_habiles_sumar('2026-08-31'::date, 1)::text d"))[0].d === "2026-09-02", "Un festivo agregado se salta al contar días hábiles");
seccion("Festivos automáticos para cualquier año (sin cargarlos a mano)");
ok((await q("select count(*)::int n from public.festivos where fecha >= '2050-01-01'"))[0].n === 0, "no hay filas de 2050 en la tabla (nadie las cargó)");
ok((await q("select public.dias_habiles_sumar('2050-12-23'::date, 2)::text d"))[0].d === "2050-12-27", "2050: tras el viernes 23 dic, el 25 es domingo festivo; 2 hábiles → martes 27");
ok((await q("select public.dias_habiles_sumar('2027-03-24'::date, 1)::text d"))[0].d === "2027-03-29", "2027: Pascua el 28 de marzo; Jueves y Viernes Santo (25 y 26) no cuentan; 1 hábil tras el miércoles 24 → lunes 29");
fin();
