import { nuevaBase, ok, seccion, fin } from "./base.mjs";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"), AN = await usuario("an@x.co", "analista_pmo"),
  G = await usuario("g@x.co"), PA = await usuario("pa@x.co"), S = await usuario("s@x.co"), I = await usuario("i@x.co"), G2 = await usuario("g2@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [PA, "patrocinador"], [S, "supervisor"], [I, "interventoria"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
const acta = (u, p, o = {}) => como(u, () => q("select public.acta_guardar($1::uuid, $2::jsonb)", [p, JSON.stringify({ proposito: "Construir", presupuesto_estimado: "1000000000", equipo_n: "8", ...o })]));

seccion("Acta de constitución");
await acta(G, P1);
ok((await q("select proposito, presupuesto_estimado::text p, equipo_n from public.actas_constitucion where proyecto_id=$1", [P1]))[0].p === "1000000000.00", "Gerente crea el acta");
await esperaError("Supervisor no edita el acta", acta(S, P1), /permiso/);
await esperaError("Gerente de otro proyecto no edita", acta(G2, P1), /permiso/);
await esperaError("Presupuesto no numérico rechazado", acta(G, P1, { presupuesto_estimado: "mucho" }), /números válidos/);
await esperaError("Presupuesto negativo rechazado", acta(G, P1, { presupuesto_estimado: "-5" }), /negativos/);
ok((await como(I, () => q("select * from public.actas_constitucion"))).length === 0, "Interventoría NO ve el acta");
ok((await como(S, () => q("select * from public.actas_constitucion"))).length === 1, "Supervisor sí ve el acta");
ok((await como(G2, () => q("select * from public.actas_constitucion"))).length === 0, "Gerente de otro proyecto no la ve");
await como(G, () => q("select public.acta_firmar($1::uuid,'gerente')", [P1]));
await esperaError("Gerente no firma como patrocinador", como(G, () => q("select public.acta_firmar($1::uuid,'patrocinador')", [P1])), /patrocinador/);
await como(PA, () => q("select public.acta_firmar($1::uuid,'patrocinador')", [P1]));
const f = (await q("select firma_gerente, firma_patrocinador from public.actas_constitucion where proyecto_id=$1", [P1]))[0];
ok(f.firma_gerente && f.firma_patrocinador, "Ambas firmas registradas");
await acta(G, P1);
ok((await q("select firma_gerente from public.actas_constitucion where proyecto_id=$1", [P1]))[0].firma_gerente !== null, "Guardar sin cambios conserva las firmas");
await acta(G, P1, { proposito: "Otro propósito" });
const f2 = (await q("select firma_gerente, firma_patrocinador from public.actas_constitucion where proyecto_id=$1", [P1]))[0];
ok(f2.firma_gerente === null && f2.firma_patrocinador === null, "Cambiar el contenido anula las firmas");
await esperaError("Escritura directa a la tabla prohibida", como(G, () => q("update public.actas_constitucion set proposito='x'")), /permission denied/);

seccion("Mediciones EVM (caso 13.3 manual)");
const med = (u, p, fecha, b, pv, ev, ac) => como(u, () => q("select public.medicion_guardar($1::uuid,$2::date,$3::numeric,$4::numeric,$5::numeric,$6::numeric)", [p, fecha, b, pv, ev, ac]));
await med(G, P1, "2026-03-31", "1000000000", "400000000", "360000000", "400000000");
const m = (await q("select bac::text, pv::text, ev::text, ac::text, origen from public.mediciones_evm where proyecto_id=$1", [P1]))[0];
ok(m.bac === "1000000000.00" && m.ev === "360000000.00" && m.origen === "manual", "Gerente registra medición");
await med(AN, P1, "2026-03-31", "1000000000", "400000000", "370000000", "400000000");
ok((await q("select count(*)::int n, max(ev)::text e from public.mediciones_evm where proyecto_id=$1", [P1]))[0].e === "370000000.00", "Analista PMO puede registrar; misma fecha corrige (no duplica)");
await esperaError("Supervisor no registra", med(S, P1, "2026-04-30", "1", "1", "1", "1"), /permiso/);
await esperaError("Director solo ve, no registra", med(D, P1, "2026-04-30", "1", "1", "1", "1"), /permiso/);
await esperaError("Valores negativos rechazados", med(G, P1, "2026-04-30", "1000", "-1", "1", "1"), /negativos/);
await esperaError("PV mayor al BAC rechazado", med(G, P1, "2026-04-30", "1000", "2000", "1", "1"), /no pueden superar/);
await esperaError("BAC cero rechazado", med(G, P1, "2026-04-30", "0", "0", "0", "0"), /mayor que cero/);
ok((await como(D, () => q("select * from public.mediciones_evm"))).length === 1, "Director ve las mediciones");
ok((await como(I, () => q("select * from public.mediciones_evm"))).length === 0, "Interventoría no ve mediciones");
ok((await como(G2, () => q("select * from public.mediciones_evm"))).length === 0, "Otro gerente no ve las de P1");
const id = (await q("select id from public.mediciones_evm where proyecto_id=$1", [P1]))[0].id;
await esperaError("Supervisor no borra", como(S, () => q("select public.medicion_borrar($1::uuid)", [id])), /permiso/);
await como(G, () => q("select public.medicion_borrar($1::uuid)", [id]));
ok((await q("select count(*)::int n from public.mediciones_evm"))[0].n === 0, "Gerente borra su medición");
ok((await q("select count(*)::int n from public.auditoria where tabla='mediciones_evm'"))[0].n >= 3, "Mediciones quedan auditadas");
fin();
