import { nuevaBase, ok, seccion, fin, asignarInterventor } from "./base.mjs";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"), AN = await usuario("an@x.co", "analista_pmo"),
  G = await usuario("g@x.co"), PA = await usuario("pa@x.co"), S = await usuario("s@x.co"), I = await usuario("i@x.co"), G2 = await usuario("g2@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [PA, "patrocinador"], [S, "supervisor"], [I, "interventoria"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
await asignarInterventor(q, P1, I);
const fn = (u, n, ...a) => como(u, () => q(`select public.${n}(${a.map((_, i) => "$" + (i + 1)).join(",")}) as r`, a));

seccion("Reportes semanales");
await como(G, () => q("select public.medicion_guardar($1::uuid,'2026-03-31'::date,1000000000,400000000,360000000,400000000)", [P1]));
const rid = (await fn(G, "reporte_crear", P1, "2026-04-02"))[0].r;
const rep = (await q("select anio, semana, proxima_revision::text pr, estado_reportado e from public.reportes_semanales where id=$1", [rid]))[0];
ok(rep.anio === 2026 && rep.semana === 14 && rep.pr === "2026-04-09" && rep.e === "verde", "Borrador: semana ISO 14 de 2026, próxima revisión +7 días");
await esperaError("No se repite la semana", fn(G, "reporte_crear", P1, "2026-04-03"), /Ya existe/);
await esperaError("Supervisor no crea reportes", fn(S, "reporte_crear", P1, "2026-04-09"), /permiso/);
await esperaError("Estado inválido rechazado", fn(G, "reporte_guardar", rid, JSON.stringify({ estado_reportado: "azul" })), /estado general/);
await fn(G, "reporte_guardar", rid, JSON.stringify({ estado_reportado: "amarillo", logros: "Se coló la placa", alertas: "Lluvias", decisiones_requeridas: "Aprobar adicional", proximos_hitos: "Estructura" }));
await como(G, () => q("insert into public.hitos (proyecto_id, nombre, fecha_plan, fecha_real) values ($1,'Cimentación','2026-03-31','2026-03-31')", [P1]));
await como(G, () => q("insert into public.hitos (proyecto_id, nombre, fecha_plan, fecha_real) values ($1,'Placa','2026-04-01','2026-04-01')", [P1]));
await como(G, () => q("insert into public.hitos (proyecto_id, nombre, fecha_plan, fecha_real) values ($1,'Otro','2026-04-20','2026-04-20')", [P1]));
await fn(G, "reporte_enviar", rid);
const e = (await q("select foto, enviado_en from public.reportes_semanales where id=$1", [rid]))[0];
ok(e.enviado_en && e.foto.spi === 0.9 && e.foto.cpi === 0.9 && e.foto.avance_fisico === 36 && e.foto.avance_presupuestal === 40, "La foto guarda SPI 0,90, CPI 0,90, avance físico 36 % y presupuestal 40 %");
ok(e.foto.hitos_cumplidos_semana === 2, "Cuenta solo los hitos cumplidos en la semana 30 mar–5 abr (2 de 3; el del 20 de abril no)");
await esperaError("Un reporte enviado no se edita", fn(G, "reporte_guardar", rid, JSON.stringify({ estado_reportado: "verde" })), /enviado/);
await esperaError("Ni se borra", como(A, () => q("delete from public.reportes_semanales where id=$1", [rid])), /permission denied|enviado/);
await esperaError("Ni se re-envía", fn(G, "reporte_enviar", rid), /ya fue enviado/);
await como(G, () => q("select public.medicion_guardar($1::uuid,'2026-04-02'::date,1000000000,500000000,100000000,900000000)", [P1]));
ok((await q("select foto->>'spi' s from public.reportes_semanales where id=$1", [rid]))[0].s === "0.9000", "Cambios posteriores en las mediciones NO alteran la foto enviada");
ok((await como(S, () => q("select * from public.reportes_semanales"))).length === 1, "Supervisor ve el reporte");
ok((await como(I, () => q("select * from public.reportes_semanales"))).length === 0, "Interventoría no ve reportes");
ok((await como(G2, () => q("select * from public.reportes_semanales"))).length === 0, "Otro gerente no los ve");
ok((await como(D, () => q("select * from public.reportes_semanales"))).length === 1, "Director ve los reportes");
await esperaError("Sin permiso para escribir directo", como(G, () => q("update public.reportes_semanales set logros='x'")), /permission denied/);

seccion("Hitos, reuniones, evaluación del patrocinador");
await esperaError("Supervisor no crea hitos", como(S, () => q("insert into public.hitos (proyecto_id, nombre, fecha_plan) values ($1,'x','2026-01-01')", [P1])), /row-level/);
ok((await como(I, () => q("select * from public.hitos"))).length === 3, "Interventoría sí ve los hitos");
await esperaError("Cancelado y con fecha real es incoherente", como(G, () => q("insert into public.hitos (proyecto_id, nombre, fecha_plan, fecha_real, cancelado) values ($1,'x','2026-01-01','2026-01-02',true)", [P1])), /check|violates/);
await como(G, () => q("insert into public.reuniones (proyecto_id, fecha, tipo, tiene_acta) values ($1,'2026-04-01','Comité',true)", [P1]));
ok((await como(I, () => q("select * from public.reuniones"))).length === 0, "Interventoría no ve reuniones");
await fn(PA, "evaluacion_patrocinador_guardar", P1, "2026-04-17", 4);
await fn(G, "evaluacion_patrocinador_guardar", P1, "2026-04-02", 5);
const ev = await q("select mes::text m, puntaje from public.evaluaciones_patrocinador where proyecto_id=$1", [P1]);
ok(ev.length === 1 && ev[0].m === "2026-04-01" && ev[0].puntaje === 5, "Una evaluación por mes (la fecha se normaliza al día 1; se corrige)");
await esperaError("Puntaje 6 rechazado", fn(G, "evaluacion_patrocinador_guardar", P1, "2026-05-01", 6), /entre 1 y 5/);
await esperaError("Supervisor no evalúa", fn(S, "evaluacion_patrocinador_guardar", P1, "2026-05-01", 3), /Solo el gerente/);
fin();
