import { nuevaBase, ok, seccion, fin, asignarInterventor } from "./base.mjs";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"),
  G = await usuario("g@x.co"), S = await usuario("s@x.co"), I = await usuario("i@x.co"), G2 = await usuario("g2@x.co"), C = await usuario("c@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [S, "supervisor"], [I, "interventoria"], [C, "consulta"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
await asignarInterventor(q, P1, I);
const tarea = (u, p, n, ini, dur, peso, av = 0) => como(u, () => q("insert into public.tareas (proyecto_id, nombre, semana_inicio, duracion_semanas, peso_pct, avance_pct) values ($1,$2,$3,$4,$5,$6) returning id", [p, n, ini, dur, peso, av])).then(r => r[0].id);
const med = async (p, fecha) => (await q("select bac::text b, pv::text pv, ev::text ev, ac::text ac, origen from public.mediciones_evm where proyecto_id=$1 and fecha_corte=$2", [p, fecha]))[0];

seccion("Permisos de tareas");
const t1 = await tarea(G, P1, "Preliminares", 1, 2, 3, 100);
await esperaError("Supervisor no crea tareas", tarea(S, P1, "x", 1, 1, 1), /row-level/);
await esperaError("Otro gerente no crea en P1", tarea(G2, P1, "x", 1, 1, 1), /row-level/);
await esperaError("Peso 101 rechazado", tarea(G, P1, "x", 1, 1, 101), /check|violates/);
await esperaError("Duración 0 rechazada", tarea(G, P1, "x", 1, 0, 1), /check|violates/);
ok((await como(I, () => q("select * from public.tareas"))).length === 1, "Interventoría lee las tareas");
ok((await como(C, () => q("select * from public.tareas"))).length === 1, "Consulta lee las tareas");
await como(S, () => q("select public.tarea_avance_guardar($1::uuid, 50)", [t1]));
ok((await q("select avance_pct::text a from public.tareas where id=$1", [t1]))[0].a === "50.00", "Supervisor actualiza el avance");
await esperaError("Consulta no actualiza avance", como(C, () => q("select public.tarea_avance_guardar($1::uuid, 10)", [t1])), /Solo el supervisor/);
await esperaError("Avance 101 rechazado", como(S, () => q("select public.tarea_avance_guardar($1::uuid, 101)", [t1])), /entre 0 y 100/);
await esperaError("El gerente no puede escribir el avance verificado directo", como(G, () => q("update public.tareas set avance_verificado_pct=5 where id=$1", [t1])), /permission denied/);
await esperaError("El supervisor no verifica", como(S, () => q("select public.tarea_verificar($1::uuid, 10, 'nota')", [t1])), /interventoría/);
await esperaError("Verificar exige nota", como(I, () => q("select public.tarea_verificar($1::uuid, 10, '')", [t1])), /nota/);
await como(I, () => q("select public.tarea_verificar($1::uuid, 40, 'Revisado en sitio')", [t1]));
const v = (await q("select avance_verificado_pct::text a, verificado_por, nota_verificacion from public.tareas where id=$1", [t1]))[0];
ok(v.a === "40.00" && v.verificado_por === I, "Interventoría registra avance verificado con su nota");
ok((await q("select count(*)::int n from public.auditoria where tabla='tareas' and campo='avance_pct'"))[0].n >= 1, "Los cambios de avance quedan auditados");
await como(G, () => q("update public.tareas set avance_pct=100 where id=$1", [t1]));
await como(I, () => q("select public.tarea_verificar($1::uuid, 100, 'Revisado ok')", [t1]));

seccion("Caso 13.2 y 13.10: avance físico y verificado");
await como(A, () => q("delete from public.tareas where proyecto_id=$1", [P1]));
const tp = await tarea(G, P1, "Preliminares", 1, 2, 3, 100), tc = await tarea(G, P1, "Cimentación", 3, 4, 17, 100), te = await tarea(G, P1, "Estructura", 7, 10, 30, 30);
await tarea(G, P1, "Resto", 17, 20, 50, 0);
await como(G, () => q("select public.linea_base_aprobar_presupuesto($1::uuid, 1000000000, 'Presupuesto aprobado')", [P1]));
await esperaError("La línea base inicial no se repite", como(G, () => q("select public.linea_base_aprobar_presupuesto($1::uuid, 5)", [P1])), /ya tiene/);
await esperaError("Supervisor no aprueba presupuesto", como(S, () => q("select public.linea_base_aprobar_presupuesto($1::uuid, 5)", [P2])), /permiso/);
await como(G, () => q("select public.medicion_calcular($1::uuid, '2027-06-30'::date)", [P1]));
let m = await med(P1, "2027-06-30");
ok(m.ev === "290000000.00" && m.origen === "calculado", "Caso 13.2: avance 3 + 17 + 9 = 29 % → EV 290.000.000 sobre BAC 1.000.000.000");
await como(I, () => q("select public.tarea_verificar($1::uuid, 20, 'En sitio se ve 20 %')", [te]));
await como(I, () => q("select public.tarea_verificar($1::uuid, 100, 'Revisado ok')", [tp]));
await como(I, () => q("select public.tarea_verificar($1::uuid, 100, 'Revisado ok')", [tc]));
await como(G, () => q("select public.medicion_calcular($1::uuid, '2027-06-30'::date)", [P1]));
m = await med(P1, "2027-06-30");
ok(m.ev === "260000000.00", "Caso 13.10: con avance verificado (26 %) el EV es 260.000.000");
await como(A, () => q("select public.parametro_guardar('global', null, 'ev_usa_avance_verificado', 'no')"));
await como(G, () => q("select public.medicion_calcular($1::uuid, '2027-06-30'::date)", [P1]));
ok((await med(P1, "2027-06-30")).ev === "290000000.00", "Con el parámetro en 'no', el EV usa el avance reportado (290.000.000)");

seccion("Caso 13.3 con valores calculados: coincide con la captura manual");
const P3 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 3','2026-01-01',12) returning id")))[0].id;
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P3, G2]));
await como(G2, () => q("insert into public.tareas (proyecto_id, nombre, semana_inicio, duracion_semanas, peso_pct, avance_pct) values ($1,'Obra',1,10,100,36)", [P3]));
await como(G2, () => q("select public.linea_base_aprobar_presupuesto($1::uuid, 1000000000)", [P3]));
await como(G2, () => q("select public.gasto_registrar($1::uuid, 1, 400000000, null)", [P3]));
await como(G2, () => q("select public.medicion_calcular($1::uuid, '2026-01-29'::date)", [P3]));
m = await med(P3, "2026-01-29");
ok(m.b === "1000000000.00" && m.pv === "400000000.00" && m.ev === "360000000.00" && m.ac === "400000000.00", "BAC 1.000 M, PV 400 M (4 de 10 semanas), EV 360 M, AC 400 M → SPI 0,90 y CPI 0,90");

seccion("Reglas de la medición calculada");
await como(G2, () => q("select public.medicion_guardar($1::uuid,'2026-02-05'::date,1000000000,500000000,100000000,100000000)", [P3]));
await como(G2, () => q("select public.medicion_calcular($1::uuid, '2026-02-05'::date)", [P3]));
ok((await med(P3, "2026-02-05")).origen === "manual", "Una medición manual de la misma fecha no se pisa");
await como(G2, () => q("select public.medicion_calcular($1::uuid, '2026-01-29'::date)", [P3]));
ok((await q("select count(*)::int n from public.mediciones_evm where proyecto_id=$1 and fecha_corte='2026-01-29'", [P3]))[0].n === 1, "Recalcular el mismo día corrige, no duplica");
await como(G, () => q("select public.medicion_calcular($1::uuid, '2026-01-01'::date)", [P2]).catch(() => {}));
await como(A, () => q("select public.medicion_calcular($1::uuid, '2026-01-10'::date)", [P2]));
ok((await q("select count(*)::int n from public.mediciones_evm where proyecto_id=$1", [P2]))[0].n === 0, "Sin tareas ni línea base no se calcula nada");
await esperaError("Ajeno no calcula", como(G2, () => q("select public.medicion_calcular($1::uuid, '2026-01-10'::date)", [P1])), /acceso/);
await como(G2, () => q("select public.medicion_calcular($1::uuid, '2026-01-05'::date)", [P3]));
const m0 = await med(P3, "2026-01-05");
ok(m0.pv === "57142857.14", `PV a los 4 días (k = 4/7 semanas): 1.000 M × 0,5714/10 = ${m0.pv}`);
fin();
