import { nuevaBase, ok, seccion, fin } from "./base.mjs";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"), F = await usuario("f@x.co", "finanzas"),
  G = await usuario("g@x.co"), S = await usuario("s@x.co"), G2 = await usuario("g2@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [S, "supervisor"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
const fn = (u, n, ...a) => como(u, () => q(`select public.${n}(${a.map((x, i) => "$" + (i + 1) + (typeof x === "number" ? "::numeric" : "")).join(",")}) as r`, a));
const crearC = (u, p, o = {}) => como(u, () => q("select public.contrato_crear($1::uuid,$2::jsonb) as id", [p, JSON.stringify({ tipo: "obra", contratista: "Constructora X", objeto: "Obra civil", valor: "480000000", ...o })])).then(r => r[0].id);
const cinfo = async (id) => (await q("select valor::text v, anticipo_pct::text ap, anticipo_valor::text av, retencion_pct::text rp, retencion_liberada rl, anticipo_autorizado_por aut from public.contratos where id=$1", [id]))[0];

seccion("Contratos");
const C1 = await crearC(G, P1);
let c = await cinfo(C1);
ok(c.v === "480000000.00" && c.rp === "10.00" && c.ap === "0.00", "Contrato creado con retención vigente 10 % y sin anticipo");
await esperaError("Supervisor no crea contratos", crearC(S, P1), /permiso/);
await esperaError("Valor cero rechazado", crearC(G, P1, { valor: "0" }), /mayor que cero/);
await esperaError("Tipo inválido rechazado", crearC(G, P1, { tipo: "raro" }), /no válido/);
ok((await como(F, () => q("select * from public.contratos"))).length === 1, "Finanzas ve el contrato");
ok((await como(S, () => q("select * from public.contratos"))).length === 1, "Supervisor ve el contrato");
ok((await como(G2, () => q("select * from public.contratos where proyecto_id=$1", [P1]))).length === 0, "Otro gerente no lo ve");
await como(A, () => q("select public.parametro_guardar('global', null, 'retencion_garantia_pct', '8')"));
const C1b = await crearC(G, P1, { valor: "100000000" });
ok((await cinfo(C1b)).rp === "8.00" && (await cinfo(C1)).rp === "10.00", "Cada contrato conserva la retención vigente al crearse (8 % nuevo, 10 % el anterior)");
await como(A, () => q("select public.parametro_guardar('global', null, 'retencion_garantia_pct', '10')"));

seccion("Anticipo discrecional");
await esperaError("El gerente no autoriza anticipos", fn(G, "contrato_anticipo_autorizar", C1, 20, "Urgente"), /director general/);
await esperaError("El administrador tampoco por defecto", fn(A, "contrato_anticipo_autorizar", C1, 20, "Urgente"), /director general/);
await esperaError("Más del máximo (20 %) rechazado", fn(D, "contrato_anticipo_autorizar", C1, 25, "Urgente"), /no puede superar/);
await esperaError("El motivo es obligatorio", fn(D, "contrato_anticipo_autorizar", C1, 20, ""), /motivo/);
const aviso0 = (await fn(D, "contrato_anticipo_autorizar", C1, 20, "Urgencia del suministro de acero"))[0].r;
c = await cinfo(C1);
ok(c.ap === "20.00" && c.av === "96000000.00" && c.aut === D, "Director autoriza 20 %: anticipo 96.000.000 y queda quién lo autorizó");
ok(aviso0 === null, "Contrato de 480 M (sobre el umbral de 350 M): sin advertencia");
const aviso1 = (await fn(D, "contrato_anticipo_autorizar", C1b, 10, "Necesidad urgente"))[0].r;
ok(typeof aviso1 === "string" && aviso1.includes("Atención"), "Contrato de 100 M (bajo el umbral): advierte pero permite");
ok((await q("select anticipo_motivo m from public.contratos where id=$1", [C1b]))[0].m === "Necesidad urgente", "Queda el motivo");
await fn(D, "contrato_anticipo_autorizar", C1b, 0, "");
ok((await cinfo(C1b)).av === "0.00", "El director puede dejar el anticipo en 0");

seccion("Caso 13.1: actas de pago");
const acta = (u, ct, f, b) => fn(u, "acta_pago_crear", ct, f, b);
const a1 = (await acta(G, C1, "2026-03-31", 120000000))[0].r;
const a2 = (await acta(G, C1, "2026-04-30", 150000000))[0].r;
const filas = await q("select numero, valor_bruto::text b, amortizacion::text am, retencion::text r, neto::text n from public.actas_pago where contrato_id=$1 order by numero", [C1]);
ok(filas[0].b === "120000000.00" && filas[0].am === "24000000.00" && filas[0].r === "12000000.00" && filas[0].n === "84000000.00", "Acta 1: bruto 120 M, amortización 24 M, retención 12 M, neto 84 M");
ok(filas[1].am === "30000000.00" && filas[1].r === "15000000.00" && filas[1].n === "105000000.00", "Acta 2: amortización 30 M, retención 15 M, neto 105 M");
const tot = (await q("select sum(valor_bruto)::text b, sum(amortizacion)::text a, sum(retencion)::text r, sum(neto)::text n from public.actas_pago where contrato_id=$1", [C1]))[0];
ok(tot.b === "270000000.00" && tot.a === "54000000.00" && tot.r === "27000000.00" && tot.n === "189000000.00", "Totales: 270 M, 54 M, 27 M, 189 M");
ok(96000000 - Number(tot.a) === 42000000 && 96000000 + Number(tot.n) === 285000000, "Anticipo pendiente 42 M; desembolsado 285 M (anticipo + netos)");
await esperaError("El anticipo no se cambia con actas radicadas", fn(D, "contrato_anticipo_autorizar", C1, 10, "x"), /ya tiene actas/);
await esperaError("La suma de actas no supera el valor del contrato", acta(G, C1, "2026-05-31", 300000000), /superaría/);
await esperaError("Valor cero rechazado", acta(G, C1, "2026-05-31", 0), /mayor que cero/);
await esperaError("Supervisor no radica", acta(S, C1, "2026-05-31", 1000), /permiso/);
await esperaError("Escritura directa prohibida", como(G, () => q("update public.actas_pago set neto=1")), /permission denied/);

seccion("Amortización con anticipo casi agotado");
const C2 = await crearC(G, P1, { valor: "1000000000" });
await fn(D, "contrato_anticipo_autorizar", C2, 20, "Urgencia");
await acta(G, C2, "2026-03-01", 900000000);
const x1 = (await q("select amortizacion::text a from public.actas_pago where contrato_id=$1 order by numero", [C2])).map(r => r.a);
ok(x1[0] === "180000000.00", "Acta de 900 M: amortiza 20 % = 180 M");
await acta(G, C2, "2026-04-01", 100000000);
ok((await q("select amortizacion::text a from public.actas_pago where contrato_id=$1 order by numero desc limit 1", [C2]))[0].a === "20000000.00", "Última acta de 100 M: amortiza 20 M (el anticipo pendiente es 200 − 180 = 20 M)");
ok((await q("select sum(amortizacion)::text a from public.actas_pago where contrato_id=$1", [C2]))[0].a === "200000000.00", "Nunca se amortiza más que el anticipo");

seccion("Estados del acta");
await esperaError("Supervisor no cambia estados", fn(S, "acta_pago_estado", a1, "aprobada_pago"), /Solo el gerente/);
await fn(G, "acta_pago_estado", a1, "en_revision_interventoria");
await fn(G, "acta_pago_estado", a1, "aprobada_pago");
ok((await q("select estado from public.actas_pago where id=$1", [a1]))[0].estado === "aprobada_pago", "Sin interventoría asignada, el gerente aprueba para pago");
await esperaError("Aprobada no se cambia", fn(G, "acta_pago_estado", a1, "radicada"), /ya está aprobada/);
await esperaError("Aprobada no se borra", fn(G, "acta_pago_borrar", a1), /aprobada/);
await esperaError("Solo se borra la última", fn(G, "acta_pago_borrar", a1), /./);
await fn(G, "acta_pago_borrar", a2);
ok((await q("select count(*)::int n from public.actas_pago where contrato_id=$1", [C1]))[0].n === 1, "Se borra la última acta no aprobada");
await acta(G, C1, "2026-04-30", 150000000);
ok((await q("select numero from public.actas_pago where contrato_id=$1 order by numero desc limit 1", [C1]))[0].numero === 2, "La numeración sigue en 2");

seccion("Retención");
await esperaError("No se libera antes del 100 %", fn(G, "contrato_retencion_liberar", C1, true), /100 %/);
await acta(G, C1, "2026-06-30", 210000000);
const aF = (await q("select id from public.actas_pago where contrato_id=$1 order by numero desc limit 1", [C1]))[0].id;
await fn(G, "contrato_retencion_liberar", C1, true);
ok((await cinfo(C1)).rl === true, "Al facturar el 100 % se libera la retención");
await esperaError("Liberada: no se radican más actas", acta(G, C1, "2026-07-31", 1000), /ya fue liberada/);
await fn(G, "contrato_retencion_liberar", C1, false);
ok((await cinfo(C1)).rl === false, "La liberación se puede revertir");
await esperaError("Supervisor no libera", fn(S, "contrato_retencion_liberar", C1, true), /permiso/);

seccion("Otrosí: un cambio aprobado ajusta el valor del contrato");
const cambio = await como(G, () => q("select public.cambio_crear($1::uuid,$2::jsonb) as id", [P1, JSON.stringify({ tipo: "Costo", descripcion_despues: "Más obra", justificacion: "Ampliación", impacto_costo: "20000000", contrato_id: C2 })])).then(r => r[0].id);
for (let i = 0; i < 4; i++) await fn(G, "cambio_avanzar", cambio, null);
const info = (await q("select nivel, base_valor::text b from public.cambios where id=$1", [cambio]))[0];
ok(info.b === "1000000000.00", "El % del cambio se mide sobre el valor del contrato (1.000 M), no sobre el BAC");
await fn(D, "cambio_decidir", cambio, "aprobar", null).catch(async (e) => { await fn(G, "cambio_decidir", cambio, "aprobar", null); });
ok((await cinfo(C2)).v === "1020000000.00", "Aprobado el cambio, el contrato pasa de 1.000 M a 1.020 M");
ok((await cinfo(C2)).av === "200000000.00", "El anticipo ya autorizado no cambia");
fin();
