import { nuevaBase, ok, seccion, fin, asignarInterventor } from "./base.mjs";
import { randomUUID } from "node:crypto";
const { q, como, esperaError, usuario } = await nuevaBase();
const A = await usuario("a@x.co", "administrador"), D = await usuario("d@x.co", "director_general"),
  G = await usuario("g@x.co"), S = await usuario("s@x.co"), I = await usuario("i@x.co"), C = await usuario("c@x.co"), G2 = await usuario("g2@x.co");
const P1 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 1','2026-01-01',12) returning id")))[0].id;
const P2 = (await como(A, () => q("insert into public.proyectos (nombre, fecha_inicio, duracion_meses) values ('Obra 2','2026-01-01',12) returning id")))[0].id;
for (const [u, r] of [[G, "gerente"], [S, "supervisor"], [I, "interventoria"], [C, "consulta"]]) await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,$3)", [P1, u, r]));
await como(A, () => q("insert into public.miembros_proyecto values ($1,$2,'gerente')", [P2, G2]));
await asignarInterventor(q, P1, I);
const T1 = (await como(G, () => q("insert into public.tareas (proyecto_id, nombre, semana_inicio, duracion_semanas, peso_pct, avance_pct) values ($1,'Estructura',1,10,100,40) returning id", [P1])))[0].id;
const hoy = new Date().toISOString().slice(0, 10);
const base = (o = {}) => ({ fecha: hoy, clima: "soleado", personal_propio: "12", personal_subcontratistas: "4", ...o });
const act = (t, av, d = "Fundida de placa") => ({ tarea_id: t, avance_dia_pct: av, descripcion: d });
const crear = (u, p, datos, acts, fotos = [], id = randomUUID()) => como(u, () => q("select public.bitacora_crear($1::uuid,$2::uuid,$3::jsonb,$4::jsonb,$5::jsonb) as id", [id, p, JSON.stringify(datos), JSON.stringify(acts), JSON.stringify(fotos)])).then(r => ({ id: r[0].id }));
const av = async (t) => (await q("select avance_pct::text a from public.tareas where id=$1", [t]))[0].a;

seccion("Entradas de la bitácora");
const id1 = randomUUID();
await crear(S, P1, base(), [act(T1, 15)], [`${P1}/${id1}/a.jpg`, `${P1}/${id1}/b.jpg`], id1);
ok(await av(T1) === "55.00", "El avance del día (15 %) se suma al de la tarea: 40 + 15 = 55");
ok((await q("select count(*)::int n from public.bitacora_fotos where bitacora_id=$1", [id1]))[0].n === 2, "Se registran las fotos");
await esperaError("Una entrada por día y por autor", crear(S, P1, base(), [act(T1, 5)]), /Ya registraste/);
ok(await av(T1) === "55.00", "La entrada rechazada no suma avance");
await crear(S, P1, base({ fecha: "2026-01-02" }), [act(T1, 70)]);
ok(await av(T1) === "100.00", "El avance suma con tope de 100 %");
await esperaError("Sin actividades se rechaza", crear(S, P1, base({ fecha: "2026-01-03" }), []), /al menos una actividad/);
await esperaError("Fecha futura rechazada", crear(S, P1, base({ fecha: "2999-01-01" }), [act(T1, 1)]), /futura/);
await esperaError("Clima inválido rechazado", crear(S, P1, base({ fecha: "2026-01-04", clima: "nieve" }), [act(T1, 1)]), /no es válido/);
await esperaError("Más de 5 fotos rechazado", crear(S, P1, base({ fecha: "2026-01-05" }), [act(T1, 1)], Array.from({ length: 6 }, (_, i) => `x${i}`)), /Máximo 5/);
const idf = randomUUID();
await esperaError("Una foto de otra entrada se rechaza", crear(S, P1, base({ fecha: "2026-01-06" }), [act(T1, 1)], [`${P1}/${randomUUID()}/a.jpg`], idf), /no corresponde/);
await esperaError("Avance del día 101 rechazado", crear(S, P1, base({ fecha: "2026-01-07" }), [act(T1, 101)]), /entre 0 y 100/);
await esperaError("Tarea de otro proyecto rechazada", crear(S, P1, base({ fecha: "2026-01-08" }), [act("11111111-1111-1111-1111-111111111111", 1)]), /no pertenece/);
await esperaError("Consulta no registra", crear(C, P1, base({ fecha: "2026-01-09" }), [act(T1, 1)]), /permiso/);
await esperaError("Otro gerente no registra en P1", crear(G2, P1, base({ fecha: "2026-01-09" }), [act(T1, 1)]), /permiso/);

seccion("Retrasos, incidentes y horas perdidas");
await esperaError("Retraso incompleto rechazado", crear(S, P1, base({ fecha: "2026-02-01", retraso_causa: "material" }), [act(T1, 0)]), /causa, las horas y la descripción/);
await esperaError("Incidente incompleto rechazado", crear(S, P1, base({ fecha: "2026-02-01", incidente_tipo: "accidente" }), [act(T1, 0)]), /tipo, la persona y la descripción/);
await crear(S, P1, base({ fecha: "2026-02-02", clima: "lluvia_fuerte", horas_perdidas_clima: "3", retraso_causa: "clima", retraso_horas: "3", retraso_descripcion: "Lluvia" }), [act(T1, 0)]);
await crear(S, P1, base({ fecha: "2026-02-03", horas_perdidas_clima: "2", retraso_causa: "material", retraso_horas: "4", retraso_descripcion: "Faltó cemento", incidente_tipo: "casi_accidente", incidente_persona: "Operario", incidente_descripcion: "Caída de herramienta" }), [act(T1, 0)]);
const h = await q("select fecha::text f, horas_perdidas_total::text t from public.bitacoras where proyecto_id=$1 and fecha in ('2026-02-02','2026-02-03') order by fecha", [P1]);
ok(h[0].t === "3.0", "Retraso por clima: las horas no se cuentan dos veces (3 h, no 6)");
ok(h[1].t === "6.0", "Retraso por material: horas por clima (2) + horas del retraso (4) = 6");

seccion("Visibilidad e inmutabilidad");
ok((await como(C, () => q("select * from public.bitacoras"))).length > 0, "Consulta ve la bitácora");
ok((await como(I, () => q("select * from public.bitacoras"))).length > 0, "Interventoría ve la bitácora");
ok((await como(G2, () => q("select * from public.bitacoras where proyecto_id=$1", [P1]))).length === 0, "Otro gerente no la ve");
await esperaError("No se edita directo", como(S, () => q("update public.bitacoras set clima='nublado'")), /permission denied/);
await esperaError("No se borra", como(A, () => q("delete from public.bitacoras")), /permission denied/);

seccion("Interventoría: entradas propias, visto bueno y comentarios");
const tavAntes = await av(T1);
await crear(I, P1, base({ fecha: "2026-03-01" }), [act(T1, 0, "Verificación en sitio")]);
const ei = (await q("select es_interventoria e from public.bitacoras where fecha='2026-03-01'"))[0];
ok(ei.e === true, "La entrada de la interventoría queda marcada como tal");
const idI = randomUUID();
await crear(I, P1, base({ fecha: "2026-03-02" }), [act(T1, 30, "Intento de mover el avance")], [], idI);
ok(await av(T1) === tavAntes, "Las entradas de interventoría NO mueven el avance de las tareas");
const bS = (await q("select id from public.bitacoras where fecha='2026-01-02'"))[0].id;
await como(I, () => q("select public.bitacora_comentar($1::uuid,'visto_bueno',null)", [bS]));
await como(I, () => q("select public.bitacora_comentar($1::uuid,'comentario','Falta foto del vaciado')", [bS]));
await como(G, () => q("select public.bitacora_comentar($1::uuid,'comentario','Se corrige mañana')", [bS]));
ok((await q("select count(*)::int n from public.bitacora_comentarios where bitacora_id=$1", [bS]))[0].n === 3, "Visto bueno y comentarios fechados");
await esperaError("El gerente no da visto bueno", como(G, () => q("select public.bitacora_comentar($1::uuid,'visto_bueno',null)", [bS])), /permiso/);
await esperaError("El supervisor no comenta", como(S, () => q("select public.bitacora_comentar($1::uuid,'comentario','x')", [bS])), /permiso/);
await esperaError("Comentario vacío rechazado", como(I, () => q("select public.bitacora_comentar($1::uuid,'comentario','')", [bS])), /Escribe/);

seccion("Archivos (Storage): solo con acceso al proyecto");
await como(A, () => q("insert into storage.objects (bucket_id, name) values ('bitacora', $1)", [`${P1}/${randomUUID()}/f.jpg`]));
await q("insert into storage.objects (bucket_id, name) values ('bitacora', $1)", [`${P2}/${randomUUID()}/f.jpg`]).catch(() => {});
await esperaError("El supervisor sube a su proyecto", (async () => { await como(S, () => q("insert into storage.objects (bucket_id, name) values ('bitacora', $1)", [`${P1}/${randomUUID()}/s.jpg`])); throw new Error("subió"); })(), /subió/);
await esperaError("El supervisor no sube a otro proyecto", como(S, () => q("insert into storage.objects (bucket_id, name) values ('bitacora', $1)", [`${P2}/${randomUUID()}/s.jpg`])), /row-level/);
await esperaError("Consulta no sube archivos", como(C, () => q("insert into storage.objects (bucket_id, name) values ('bitacora', $1)", [`${P1}/${randomUUID()}/c.jpg`])), /row-level/);
await esperaError("Ruta mal formada no sube", como(S, () => q("insert into storage.objects (bucket_id, name) values ('bitacora', 'basura/x.jpg')")), /row-level/);
ok((await como(C, () => q("select * from storage.objects where bucket_id='bitacora'"))).length >= 1, "Consulta ve los archivos de su proyecto");
ok((await como(G2, () => q("select * from storage.objects where name like $1", [`${P1}/%`]))).length === 0, "Otro gerente no ve los archivos de P1");
ok((await q("select public from storage.buckets where id='bitacora'"))[0].public === false, "El bucket es privado");
fin();
